using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Class1_NS;
namespace Class1_NS
{
    [TestFixture]
    public class Class1_tests
    {
        [Test]
        public void Method1_test()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}