using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using Tests.Class2_and_3_NS;
namespace Tests.Class2_and_3_NS
{
    [TestFixture]
    public class Class3_tests
    {
        [Test]
        public void Method2_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}