using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using TestGeneratorLibrary.GeneratedValuesInfo;

namespace TestGeneratorLibrary
{
    public class CodeGenerator
    {
        public static List<CsFileInfo> Generate(List<NameSpaceInfo> nsInfo, List<UsingDirectiveSyntax> usings)
        {
            var result = new List<CsFileInfo>();

            var generatedUsingsDeclaration = GenerateUsingsDeclaration(nsInfo, usings);
            foreach (var ns in nsInfo)
            {

                var generatedNsDeclaration = GenerateNsDeclaration(ns);
                foreach (var innerClass in ns.Classes)
                {
                    var generatedClassDeclaration = GenerateClassDeclaration(innerClass);
                    string fileName = ns.Name + "_" + innerClass.Name + "_autogenerated_" + result.Count.ToString() + ".cs";
                    string fileContent = generatedUsingsDeclaration.NormalizeWhitespace().ToFullString()
                        + "\r\n"
                        + generatedNsDeclaration.WithMembers(generatedClassDeclaration).NormalizeWhitespace().ToFullString();
                    result.Add(new CsFileInfo(fileName, fileContent));
                }
            }
            return result;
        }

        private static CompilationUnitSyntax GenerateUsingsDeclaration(List<NameSpaceInfo> nsInfo, List<UsingDirectiveSyntax> usings)
        {
            return SyntaxFactory.CompilationUnit().WithUsings(GetUsings(nsInfo, usings));
        }

        private static NamespaceDeclarationSyntax GenerateNsDeclaration(NameSpaceInfo ns)
        {
            return SyntaxFactory.NamespaceDeclaration(SyntaxFactory.IdentifierName(ns.Name));
        }

        private static SyntaxList<MemberDeclarationSyntax> GenerateClassDeclaration(ClassInfo classInfo)
        {
            var result = new SyntaxList<MemberDeclarationSyntax>();
            result = result.Add(SyntaxFactory.ClassDeclaration(classInfo.Name + "_tests")
                .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                        .WithAttributeLists(
                            SyntaxFactory.SingletonList(
                                SyntaxFactory.AttributeList(
                                    SyntaxFactory.SingletonSeparatedList(
                                        SyntaxFactory.Attribute(
                                            SyntaxFactory.IdentifierName(
                                                "TestFixture"))))))
                        .WithMembers(GetTestMethods(classInfo)));
            return result;
        }

        private static SyntaxList<UsingDirectiveSyntax> GetUsings(List<NameSpaceInfo> namespaces, List<UsingDirectiveSyntax> classUsings)
        {
            classUsings.Add(
                SyntaxFactory.UsingDirective(
                    SyntaxFactory.QualifiedName(
                        SyntaxFactory.IdentifierName("NUnit"),
                        SyntaxFactory.IdentifierName("Framework"))));

            foreach (var namespaceInfo in namespaces)
            {
                classUsings.Add(
                    SyntaxFactory.UsingDirective(
                        SyntaxFactory.IdentifierName(namespaceInfo.Name)));
            }

            return new SyntaxList<UsingDirectiveSyntax>().AddRange(classUsings);
        }

        private static SyntaxList<MemberDeclarationSyntax> GetTestMethods(ClassInfo innerClass)
        {
            var testMethods = new List<MemberDeclarationSyntax>();

            foreach (var method in innerClass.Methods)
            {
                testMethods.Add(SyntaxFactory.MethodDeclaration(
                    SyntaxFactory.PredefinedType(
                        SyntaxFactory.Token(SyntaxKind.VoidKeyword)
                        ),
                    SyntaxFactory.Identifier(
                        method.Name + "_test"
                        )
                    )
                .WithAttributeLists(
                    SyntaxFactory.SingletonList(
                        SyntaxFactory.AttributeList(
                            SyntaxFactory.SingletonSeparatedList(
                                SyntaxFactory.Attribute(
                                    SyntaxFactory.IdentifierName(
                                        "Test"))))))
                .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                .WithBody(SyntaxFactory.Block(SyntaxFactory.ParseStatement("Assert.Fail(\"autogenerated\");"))));
            }

            return new SyntaxList<MemberDeclarationSyntax>().AddRange(testMethods);
        }
    }
}