using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using NUnit.Framework;
using TestProject1.ClassesForTest;
namespace TestProject1.ClassesForTest
{
    [TestFixture]
    public class AuditServer_tests
    {
        [Test]
        public void Audit_test()
        {
            Assert.Fail("autogenerated");
        }
    }
}